---
- name: Write haproxy.cfg config file
  template:
    src: haproxy.cfg.j2
    dest: /tmp/haproxy.cfg
    mode: "0644"
    owner: "root"
    group: "root"
  register: wr_config

- name: Check config passes
  shell:
    cmd: "haproxy -c -f /tmp/haproxy.cfg"
  when: wr_config.changed
