---
- name: Write haproxy.cfg config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
    owner: "root"
    group: "root"
  notify:
    - Restart haproxy
  register: wr_config

- name: Check config passes
  shell:
    cmd: "haproxy -c -f /etc/haproxy/haproxy.cfg"
  when: wr_config.changed
  
- name: Set SELinux bools
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - haproxy_connect_any
    - httpd_can_network_connect
    - nis_enabled

- name: Set SELinux haproxy ports
  community.general.seport:
    ports: "{{ item.bind | regex_replace ('[^0-9]','') }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop: "{{ frontend }}"

- name: Set SELinux haproxy ports
  community.general.seport:
    ports: "{{ item.bind | regex_replace ('[^0-9]','') }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop: "{{ listen }}"

- name: Start haproxy
  service:
    name: haproxy
    state: started
