---
- name: Write haproxy.cfg config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
    owner: "root"
    group: "root"
  notify:
    - Restart haproxy
  register: wr_config

- name: Check config passes
  shell:
    cmd: "haproxy -c -f /etc/haproxy/haproxy.cfg"
  when: wr_config.changed

- name: Set SELinux haproxy bool
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: Set SELinux nis_enabled bool
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes

- name: Set SELinux haproxy ports
  community.general.seport:
    ports: "{{ item.bind }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop: "{{ frontend }}"

- name: Start haproxy
  service:
    name: haproxy
    state: started
